[package]
name = "tododo"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.68"
chrono = "0.4.23"
enum-iterator = "1.2.0"
rand = "0.8.5"
serde = { version = "1.0.151", features = ["derive"] }
serde_json = "1.0.91"